version: "3"
services:
  frontend-react:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - "VIRTUAL_HOST=${tag}.react.connect-sx.com"
      - VIRTUAL_PORT=3000


  backend-odoo:
    restart: always
    image: odoo:12
    depends_on:
      - db
    volumes:
      - "odoo-web-data-${tag}:/var/lib/odoo"
      - ./backend/config:/etc/odoo
      - ./backend/addons:/mnt/extra-addons
    environment:
      - "VIRTUAL_HOST=${tag}.odoo.connect-sx.com"
      - VIRTUAL_PORT=8069
    
  
  db:
    restart: always
    image: rahulkathpal/postgres
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "odoo-db-data-${tag}:/var/lib/postgresql/data/pgdata"
  
volumes:
  node-modules:
  "odoo-db-data-${tag}":
  "odoo-web-data-${tag}":


networks:
  default:
    external:
      name: nginx-proxy